// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrTSIB3xfe3ql7Pb1IXfsqMroqR99UYIE',
    appId: '1:737488045692:web:22e84362e2c3b7f1ae6bf9',
    messagingSenderId: '737488045692',
    projectId: 'jobnest-2c667',
    authDomain: 'jobnest-2c667.firebaseapp.com',
    storageBucket: 'jobnest-2c667.firebasestorage.app',
    measurementId: 'G-HWMZY8FS6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ2nc9qSAPTQGlXT6WheDPTEJiF-tyucw',
    appId: '1:737488045692:android:70b1e23ea56ff493ae6bf9',
    messagingSenderId: '737488045692',
    projectId: 'jobnest-2c667',
    storageBucket: 'jobnest-2c667.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQFBaPVxuAD2cXVYmW608CPUuC8HmEoLY',
    appId: '1:737488045692:ios:e17d614fd945be60ae6bf9',
    messagingSenderId: '737488045692',
    projectId: 'jobnest-2c667',
    storageBucket: 'jobnest-2c667.firebasestorage.app',
    iosBundleId: 'com.example.jobnest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQFBaPVxuAD2cXVYmW608CPUuC8HmEoLY',
    appId: '1:737488045692:ios:e17d614fd945be60ae6bf9',
    messagingSenderId: '737488045692',
    projectId: 'jobnest-2c667',
    storageBucket: 'jobnest-2c667.firebasestorage.app',
    iosBundleId: 'com.example.jobnest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrTSIB3xfe3ql7Pb1IXfsqMroqR99UYIE',
    appId: '1:737488045692:web:2e4e55975fe31859ae6bf9',
    messagingSenderId: '737488045692',
    projectId: 'jobnest-2c667',
    authDomain: 'jobnest-2c667.firebaseapp.com',
    storageBucket: 'jobnest-2c667.firebasestorage.app',
    measurementId: 'G-TVVVN4DNFB',
  );
}
